spring:
  datasource:
    url: jdbc:postgresql://test-db:5432/ai_creation
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: 2

logging:
  level:
    com.aicreation: info
    org.springframework.web: info
    org.mybatis: info 