spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ai_creation
    username: postgres
    password: 123456
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      
  redis:
    host: localhost
    port: 6379
    password: 
    database: 1

logging:
  level:
    com.aicreation: debug
    org.springframework.web: debug
    org.mybatis: debug 