spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: 0

logging:
  level:
    com.aicreation: warn
    org.springframework.web: warn
    org.mybatis: warn
  file:
    max-size: 100MB
    max-history: 30 